apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: oficina
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "sua-chave-aqui"
  POSTGRES_DB: "oficina"
  POSTGRES_USER: "oficina_admin"
  POSTGRES_PASSWORD: "sua-senha"
