apiVersion: v1
kind: Secret
metadata:
  name: oficina-secret
  namespace: oficina
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "sua-chave-aqui"
  DB_NAME: "oficina"
  DB_USER: "seu-usuario"
  DB_PASSWORD: "sua-senha"
