apiVersion: v1
kind: Service
metadata:
  name: oficina-app
  namespace: oficina

spec:
  selector:
    app: oficina-app

  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP

  type: ClusterIP
